from oslo.torch.optim.cpu_adagrad import CPUAdagrad
from oslo.torch.optim.cpu_adam import CPUAdam
from oslo.torch.optim.zero_redundancy_optimizer import ZeroRedundancyOptimizer
from oslo.torch.optim.fused_adam import FusedAdam
from oslo.torch.optim.fused_adagrad import FusedAdagrad
from oslo.torch.optim.fused_sgd import FusedSGD
from oslo.torch.optim.fused_novograd import FusedNovoGrad
from oslo.torch.optim.fused_lamb import FusedLamb
from oslo.torch.optim.fused_mixed_precision_lamb import FusedMixedPrecisionLamb
